FROM plone:5.0 as robot_tests
USER root
RUN apt-get update && apt-get install -y --no-install-recommends curl git libyaml-dev zlib1g-dev libjpeg-dev gcc  build-essential autoconf  libxml2-dev libxslt1-dev libsasl2-dev  libssl-dev
# libjpeg-turbo8-dev
#virtualenv
# python-dev

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 6.1

# Install nvm with node and npm
RUN ["/bin/bash","-c", "curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash \
    && ls /usr/local/nvm \
    && source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default \
    && npm i -g npm@3 \
    && npm i -g typescript@2.1.4 \ 
    && npm cache clean \
    && npm set registry http://registry.npmjs.org \
    && npm update -g"]
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH
ENV ZSERVER_HOST  0.0.0.0

#RUN mkdir -p /buildout/buildout-cache/eggs /buildout/buildout-cache/downloads
#RUN addgroup appuser && useradd -r -u 1001 -g appuser appuser
#RUN chown -R appuser.appuser /buildout
#RUN printf "[buildout]\nextends=https://raw.githubusercontent.com/collective/buildout.plonetest/master/buildout-cache.cfg\nindex=https://pypi.python.org/simple/\nplone-series=5.0\nparts=\n[versions]\nPlone=5.0.8" > /buildout/download.cfg
#RUN cd /buildout && virtualenv . && bin/pip install zc.buildout==2.2.5 setuptools==8.3 && bin/buildout -c download.cfg install download install
#RUN ls /buildout/buildout-cache/eggs /buildout/buildout-cache/downloads

#RUN mkdir -p /plone/.buildout && printf "[buildout]\neggs-directory=/plone/buildout-cache/eggs\ndownload-cache=/plone/buildout-cache/downloads\n" > ~/.buildout/default.cfg


#WORKDIR /plone/instance

#COPY . /buildout/
#RUN chown -R sappuser.appuser /buildout

#USER plone
#RUN cd /buildout && bin/buildout -c travis.cfg install test resources robot instance
#RUN ["/bin/bash","-c", "source $NVM_DIR/nvm.sh && cd /buildout/ide && npm install && npm run build"]
