#docker run --rm -d -p 4444:24444 -p 7777:25900 -p 55001:55001 -p8080:8080 -v /dev/shm:/dev/shm -v $PWD/src/Products/CMFPlomino/tests/:/buildout/src/Products/CMFPlomino/tests -v $PWD/test:/buildout/parts/test --privileged --rm --name rtests robot_tests
#docker exec -ti rtests /bin/bash -c "cd /buildout; ROBOT_REMOTE_URL=http://127.0.0.1:24444/wd/hub bin/test --all"
version: '3.5'
networks:
  testnet:
services:
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-20200326
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - VNC_NO_PASSWORD=1
    ports:
      - "5900:5900"
      - "4444:4444"
    networks: 
      - testnet
#    privileged: true
  plominotest:
    image: robot_tests
    ports:
      - "8080:8080"
    environment:
      - ROBOT_REMOTE_URL=http://selenium:4444/wd/hub
      - ROBOT_PLONE_URL=http://plominotest:55001/plone
      - ROBOT_DESIRED_CAPABILITIES=platform:Linux,browserName:chrome
    volumes:
      - /dev/shm:/dev/shm
      - ./test/testoutput:/buildout/parts/test  # doesn't work with remote docker
      - ./src/Products/CMFPlomino/tests/:/buildout/src/Products/CMFPlomino/tests # doesn't work with remote docker
    networks:
      - testnet
    command: /bin/sh -c "/plone/instance/bin/test -vv -s Products.CMFPlomino && /plone/instance/bin/test --all -vv -t robot -s Products.CMFPlomino"
    depends_on:
      - "selenium"
    links:
      - selenium

  robot-server:
    image: robot_tests
    depends_on:
       - selenium
    networks:
      - testnet
    command: bin/robot-server --no-reload -v Products.CMFPlomino.testing.PRODUCTS_CMFPLOMINO_ACCEPTANCE_TESTING
    volumes:
      - /dev/shm:/dev/shm
#      - ./src/Products/CMFPlomino:/buildout/src/Products/CMFPlomino
    privileged: true
    environment:
      - ZSERVER_HOST=robot-server
      - ZSERVER_PORT=55001
      - LISTENER_PORT=49999
      - LISTENER_HOST=robot-server
  robot:
    image: robot_tests
    depends_on:
       - selenium
       - robot-server
    networks:
      - testnet
    environment:
       - LISTENER_PORT=49999
       - LISTENER_HOST=robot-server
    command: bin/robot --outputdir=/buildout/parts/test --variable=REMOTE_URL:http://selenium:4444/wd/hub --variable=PLONE_URL:http://robot-server:55001/plone  /buildout/src/Products/CMFPlomino/tests/robot/test_*.robot
    volumes:
      - /dev/shm:/dev/shm
      - ./test/testoutput:/buildout/parts/test # doesn't work with remote docker
      - ./src/Products/CMFPlomino/tests/:/buildout/src/Products/CMFPlomino/tests # doesn't work with remote docker
    privileged: true

  instance:
    image: robot_tests
    command: bin/instance fg
    ports:
      - 8080:8080
    volumes:
      - /dev/shm:/dev/shm
      - ./src/Products/CMFPlomino:/buildout/src/Products/CMFPlomino


  selenium-hub:
    image: selenium/hub:3.141.59-20200409
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  opera:
    image: selenium/node-opera:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
